name: emotion_recognition_windows
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  # PyTorch con CUDA 11.8 para Windows
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0
  - pytorch::torchaudio=2.1.0
  - pytorch::pytorch-cuda=11.8

  # Ciencia de datos y ML (versiones idénticas)
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - ipykernel=6.25.0

  # Procesamiento de imágenes y video
  - opencv=4.8.1
  - pillow=10.0.0

  # Web framework
  - flask=2.3.3
  - flask-socketio=5.3.6

  # Utilidades
  - tqdm=4.66.1
  - pyyaml=6.0.1
  - requests=2.31.0

  # pip dependencies (idénticas)
  - pip:
      - mediapipe==0.10.7
      - albumentations==1.3.1
      - wandb==0.15.12
      - tensorboard==2.14.1
      - gradio==3.50.2
